name: Build LaTeX document
on:
  push:
    branches:
      - master
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: paper
          root_file: |
            spatial_signatures.tex
            manuscript.tex
            title_page.tex

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add paper/spatial_signatures.pdf
          git add paper/manuscript.pdf
          git add paper/title_page.pdf
          git commit -m "Build PDF" -a --allow-empty

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
